### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by jigsawye**

### CODE REVIEW

**Review by tw0517tw — APPROVED** [review]

**Comment by kpman** [comment]
error TS2742: The inferred type of 'MoreIcon' cannot be named without a reference to 'hoist-non-react-statics/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.

是升了什麼造成這個問題？

**Comment by jigsawye** [comment]
我猜是 `@types/styled-components`

**Comment by kpman** [comment]
所以是要降回去嗎，不然這 PR 就掛著了好像不太好

**Comment by jigsawye** [comment]
這應該是可以手動修復的，我有空再來修它

**Comment by jigsawye** [comment]
隔了快兩個月回來把這 PR 修好

**Review by tw0517tw — APPROVED** [review]
prettier 升了耶

**Pull request merged**
